name: StopIt
version: 1.0.0
api: 1.12.0
main: StopIt\StopIt
author: deot
description: StopIt

permissions:
  stopit:
    description: "StopIt by deot (Twitter: @deotern)"
    default: false
    children:
      stopit.settime:
        description: "Set server default time value"
        default: op
