name: StopIt
version: 1.0.1
api: 1.12.0
main: StopIt\StopIt
author: deot
description: StopIt
# twitter: @deotern
# Made by deot with <3

commands:
  deftime:
    description: Sets server default time
    permission: stopit.deftime

permissions:
  stopit.deftime:
    description: Allow to use set default time command
    default: op
